title: Paulo Rogério
author: Paulo Rogério
description: >- # this means to ignore newlines until new value
  This is my personal website that I made to show my skills, content and
  other types of media. Feel free to contact me, read my blog, see my youtube
  content, i just wanna share knowledge and other useful info with people that are interested
  in the kinda of things I am.

keywords: programming, linux, kubernetes, docker, python, shell, terraform, aws
content-language: pt-br, en-US

email: psilva.gomes.rogerio@gmail.com
  
collections:
  authors:
    output: true
  category:
    output: true
  menus:
    output: true


defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "category"
    values:
      layout: "category"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "menus"
    values:
      layout: "menu"      
  - scope:
      path: ""
    values:
      layout: "default"

paginate: 5
paginate_path: "articles/page:num"

baseurl: "/" 
url: "" 

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-pdf-embed

exclude: 
  - design_offline/
  - LICENSE
  - README.md
